from __future__ import annotations

import smtplib
from email.message import EmailMessage
from pathlib import Path


class EmailNotifier:
    def __init__(
        self,
        enabled: bool,
        smtp_host: str,
        smtp_port: int,
        smtp_username: str,
        smtp_password: str,
        sender: str,
        recipients_csv: str,
        use_tls: bool,
        use_ssl: bool,
        subject_prefix: str,
        dashboard_base_url: str,
    ):
        self.enabled = enabled
        self.smtp_host = smtp_host.strip()
        self.smtp_port = int(smtp_port)
        self.smtp_username = smtp_username.strip()
        self.smtp_password = smtp_password
        self.sender = sender.strip() or self.smtp_username
        self.recipients = [x.strip() for x in recipients_csv.split(",") if x.strip()]
        self.use_tls = use_tls
        self.use_ssl = use_ssl
        self.subject_prefix = subject_prefix.strip() or "[AI Security Alert]"
        self.dashboard_base_url = dashboard_base_url.strip().rstrip("/")

    def configured(self) -> bool:
        if not self.enabled:
            return False
        if not self.smtp_host or not self.smtp_port:
            return False
        if not self.sender or not self.recipients:
            return False
        if not self.smtp_username or not self.smtp_password:
            return False
        return True

    def _build_urls(self, clip_path: Path) -> tuple[str | None, str | None]:
        if not self.dashboard_base_url:
            return None, None

        dashboard_url = f"{self.dashboard_base_url}/"
        replay_url = f"{self.dashboard_base_url}/event-clips/{clip_path.name}"
        return dashboard_url, replay_url

    def send_alert(
        self,
        *,
        event_id: str,
        threat_score: float,
        camera_name: str,
        alert_timestamp_utc: str,
        clip_path: Path,
        clip_duration_seconds: float,
    ) -> bool:
        if not self.configured():
            return False

        dashboard_url, replay_url = self._build_urls(clip_path)

        body_lines = [
            "Automated fighting alert generated by AI Security System.",
            "",
            f"Camera: {camera_name}",
            f"Threat score: {threat_score:.3f}",
            f"Timestamp (UTC): {alert_timestamp_utc}",
            f"Event ID: {event_id}",
            f"Clip duration (s): {clip_duration_seconds:.2f}",
            f"Clip file: {clip_path.name}",
        ]

        if dashboard_url:
            body_lines.append(f"Dashboard: {dashboard_url}")
        if replay_url:
            body_lines.append(f"Replay link: {replay_url}")

        body_lines.append("")
        body_lines.append("This is an automated message.")

        msg = EmailMessage()
        msg["Subject"] = f"{self.subject_prefix} {camera_name} score={threat_score:.3f}"
        msg["From"] = self.sender
        msg["To"] = ", ".join(self.recipients)
        msg.set_content("\n".join(body_lines))

        try:
            if self.use_ssl:
                with smtplib.SMTP_SSL(self.smtp_host, self.smtp_port, timeout=20) as server:
                    server.login(self.smtp_username, self.smtp_password)
                    server.send_message(msg)
            else:
                with smtplib.SMTP(self.smtp_host, self.smtp_port, timeout=20) as server:
                    server.ehlo()
                    if self.use_tls:
                        server.starttls()
                        server.ehlo()
                    server.login(self.smtp_username, self.smtp_password)
                    server.send_message(msg)
            return True
        except Exception:
            return False
